### ISSUE TITLE
ConnectMacro design issue

### ISSUE THREAD

**Issue by zabojad** [elsassph/haxe-redux#12]
Hi !

First of all, thank you for your effort to provide a decent haxe-redux and haxe-react-redux lib!

I would like to raise what I would call an issue (it's more a disagreement) about the way your ConnectMacro works.

From what I understand from the README, it actually merges the mapped parts of the global state right into the "container" component react state. Well, I've crossed many situations until now where it was very handy to have a "container state" separated from the redux state and when it's up to the developer to merge it or not (on componentWillReceiveProps for example) when needed.

Do you think you could propose a second flavor of your ConnectMacro where it would let alone the react state of the component and use instead its props to inject into it the mapped parts of the redux state?

So far, it is the only "black point" (not sure we say so in English ^^) that prevents me from using your lib.

Best,

Thomas

**Comment by zabojad** [comment]
Erf, I just realized we have a [PR going on](https://github.com/elsassph/haxe-redux/pull/6)... OK I'll cross my fingers for a happy end ^^...

**Comment by elsassph** [comment]
I agree this wasn't the best idea eventually, and it's better to keep the map in a container.

For now a good pattern is to create an explicit container class for your component.
