### ISSUE TITLE
Externs for redux-observable

### ISSUE THREAD

**Issue by zabojad** [elsassph/haxe-redux#18]
Hi,
Does any one has tried to use [redux-observable](https://redux-observable.js.org) with `haxe-redux` yet?
@kLabz maybe?

**Comment by zabojad** [comment]
Or [redux-saga](https://github.com/redux-saga) ?

**Comment by elsassph** [comment]
Both seem impractical as model for Haxe (RxJS, JS generators).

**Comment by zabojad** [comment]
Yes, it's what I was realizing after posting this here...
