### ISSUE TITLE
One Action type = one reducer ?

### ISSUE THREAD

**Issue by zabojad** [elsassph/haxe-redux#21]
Hi guys!

There one thing I do not find optimal here. I understand that a given reducer can receive only the actions from one action enum. Basically we have 1 state leaf = 1 action enum = 1 reducer.

While I'm OK with 1 state leaf = 1 reducer, I'm not really OK with the = 1 action enum part...

There are some actions that really can have consequences on more that one state leaf (I'm thinking about some `UserDidLogout` action for example that could trigger some cleaning in several leafs of the state).

On the other hand, I understand the typing need here so maybe the solution could be:
- Define a root enum `MyAppAction` of action enums and make the reducer receive a `MyAppAction` instead of their current action enum...
or
- Add to `haxe-redux` some generic batch action dispatch feature that would allow dispatching several actions without trigerring more than one state mutation (with all the performances consequences it has...). This can be implemented with a special action type and its corresponding reducer which will call the other reducer with each of the batched actions it receives. It returns in the end the result (mutated state) and triggers only one mutation. This is generic enough to be added to this library I think... I prefer this solution to the first one because batching is more powerful and allows other use cases as well.

What do you think?

**Comment by kLabz** [comment]
I guess I would handle that with a `logout` [thunk](#13), handling the needed cleanup in the logout action (thunk) by dispatching needed actions on other middleware/reducers. IIRC reducer updates are handled/optimized by reduxjs so this shouldn't be a problem.

Seems like we have opposite logic on reducer/action scope:

IMO a reducer has a list of actions that is strictly its own (add such item, empty the list, etc.) and without real complexity (no "business code", only simple instructions). The reducer does not have to know what's going on elsewhere on the application, it's none of its business.

If an action, the logout in your example, must have repercussions on several parts of the state (several reducers), then it is up to it (the action) to define these repercussions. An action `UserDidLogout` on a reducer managing the list of products seems off topic to me.

---

> This can be implemented with a special action type and its corresponding reducer which will call the other reducer with each of the batched actions it receives. It returns in the end the result (mutated state) and triggers only one mutation.

Seems like internal reduxjs to me, not sure if it belongs here (might as well implement redux itself in haxe instead of using externs?). How would this middleware (?) be able to handle nested reducers and changes in various part of the "state tree"? 

Also, why would you need the end result?

**Comment by zabojad** [comment]
> IMO a reducer has a list of actions that is strictly its own (add such item, empty the list, etc.) and without real complexity (no "business code", only simple instructions). The reducer does not have to know what's going on elsewhere on the application, it's none of its business.

Well, that's not how Redux works out of the box. Redux dispatches any action to all the reducers. What we are having here is less flexible than the original js lib.

> handling the needed cleanup in the logout action (thunk) by dispatching needed actions on other middleware/reducers. IIRC reducer updates are handled/optimized by reduxjs so this shouldn't be a problem.

It is unfortunately not what I've observed. For every action dispatched, there is a state mutation and a call to the concerned `mapStateToProps`. 

Note that it is actually a rather known issue which is usually addressed with an action batching feature:
- https://redux.js.org/faq/performance
- https://twitter.com/dan_abramov/status/656074974533459968?lang=fr
- https://stackoverflow.com/questions/41646353/react-redux-how-to-render-not-after-each-dispatch-but-after-several
- https://github.com/manaflair/redux-batch
- https://github.com/tshelburne/redux-batched-actions
- ...

My opinion is that we could propose in `haxe-redux` a generic BatchAction/BatchReducer feature as it is a common enough use case...

**Comment by elsassph** [comment]
I agree that strictly speaking redux passes all actions to all reducers, and while I wouldn't say it's a good pattern it should be somehow possible but it would really increase overall complexity.

One solution would to not use the automatic reducer mapping function (where you want to receive multiple Enums) so your reducer will receive all actions, and in the reducer you could have a sub-routing to select the enum type.

**Comment by elsassph** [comment]
Or we could add an extra reducer mapping which takes a map of enum type and reducer instead of a single one.

**Comment by zabojad** [comment]
@elsassph what about the bach actions feature? It solves the problem nicely as we keep the current behavior one reducer = one action enum = one state + it provides an out of the box solution for the batching action feature which is commonly used with "vanilla redux". Everything stays nicely typed and we offer a way to improve perfs...

**Comment by elsassph** [comment]
@zabojad batching is another topic IMHO because it's about dispatching multiple actions - not about one action to be handled by multiple reducers. Maybe create a new issue and possibly suggest how you'd think the API could look like.

**Comment by zabojad** [comment]
I'll do that in a week or two...

**Comment by zabojad** [comment]
OK, some of my darkest desires seem to have been fulfilled, despite the skepticism of some haxers around :) : https://react-redux.js.org/api/batch

**Comment by elsassph** [comment]
Uh nice :)
